### PR TITLE
Trying to Fix what was broken

### PR DESCRIPTION
**Pull request by Kostas0613**
Fixing what was broken **FIXED:**
1) Right Click on tiles
2) Stats tab page
**Remaining fixes:**
1) Add Transaction doesn't work
2) Saving price doesn't load

### CODE REVIEW

**Comment by Ekas-118** [comment]
The right click function isn't working very well:
Right-click -> Data sometimes crashes / does nothing / shows data of the wrong object
Right-click -> Delete does nothing

**Comment by Kostas0613** [comment]
Delete function is not implemented yet

**Comment by Kostas0613** [comment]
Right Click function works only when clicked directly on a Tile, not on a label in a tile

**Comment by De1xs** [comment]
@Kostas0613  darysi dar kazka ant sito ar merginam ?

**Pull request merged**
